<a href="https://colab.research.google.com/github/kiran-ks/datasciencecoursera/blob/master/HW2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
# 1. Include a section with your name
name = "Kiran Khanderao"

# 2. Create matrix A with size (3,5) containing random numbers
import numpy as np
A = np.random.randint(100, size=(3, 5))
print(A)

# 3. Find the size and length of matrix A
size_A = A.shape
length_A = len(A)
print('size of A = ', size_A)
print('length of A = ', length_A)

# 4. Resize (crop/slice) matrix A to size (3,4)
A = A[0:3, 0:4]
print('A resized = ',A)

# 5. Find the transpose of matrix A and assign it to B 
B = np.transpose(A)
print('B = ',B)

# 6. Find the minimum value in column 1 of matrix B
min_val = min(B[:,1])
print('minimum value in col 1 of B = ', min_val)

# 7. Find the minimum and maximum values for the entire matrix A
min_A = np.amin(A)
max_A = np.amax(A)
print('min of A =', min_A, ' max of A = ', max_A)

# 8. Create vector X (an array) with 4 random numbers
X= np.random.randint(100, size=4)
print('X = ', X)

# 9. Create a function and pass vector X and matrix A in it
def funct(X, A):
  print('made function with X, A')
  pass
funct(X, A)

# 10. In the new function multiply vector X with matrix A and assign the result to D (note: you may get an error! … think why and fix it. Recall matric manipulation in class!)
def function(X, A):
  D = A*X
  return D
D = function(X, A)
print('D = ', D)

# 11. Create a complex number Z with absolute and real parts != 0
Z = complex(2, 4)
print('Z = ', Z)

# 12. Show its real and imaginary parts as well as it’s absolute value
Z_real= Z.real
Z_imaginary = Z.imag
Z_abs = abs(Z)
print('Z real part = ', Z_real)
print('Z imaginary part = ', Z_imaginary)
print('Z absolute value = ', Z_abs)

# 13. Multiply result D with the absolute value of Z and record it to C
C = D*Z_abs
print('C = ', C)

# 14. Convert matrix B from a matrix to a string and overwrite B
B = np.array2string(B)
print('B = ', B)

# 15. Display a text on the screen: ‘Name is done with HW2‘, but pass your ‘Name’ as a string variable
print(name, "is done with HW2")

# 16. Organize your code: use each line from this assignment as a comment line before each step

# 17. Save all steps as a script in a .py file

# 18. Email your Github link to me including your .py file + screenshots of your running code before next class.

[[48 37 91 85 85]
 [12 15  3 19  1]
 [59 56 49 52 56]]
size of A =  (3, 5)
length of A =  3
A resized =  [[48 37 91 85]
 [12 15  3 19]
 [59 56 49 52]]
B =  [[48 12 59]
 [37 15 56]
 [91  3 49]
 [85 19 52]]
minimum value in col 1 of B =  3
min of A = 3  max of A =  91
X =  [39 84 86 16]
made function with X, A
D =  [[1872 3108 7826 1360]
 [ 468 1260  258  304]
 [2301 4704 4214  832]]
Z =  (2+4j)
Z real part =  2.0
Z imaginary part =  4.0
Z absolute value =  4.47213595499958
C =  [[ 8371.83850776 13899.39854814 34998.93598383  6082.1048988 ]
 [ 2092.95962694  5634.8913033   1153.81107639  1359.52933032]
 [10290.38483245 21036.92753232 18845.58091437  3720.81711456]]
B =  [[48 12 59]
 [37 15 56]
 [91  3 49]
 [85 19 52]]
Kiran Khanderao is done with HW2
